/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author User
 */
public class AdminUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminUI
     */
    public AdminUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jTextField1 = new javax.swing.JTextField();
                usuarioLabel = new javax.swing.JLabel();
                usuarioLabel1 = new javax.swing.JLabel();
                usuarioLabel2 = new javax.swing.JLabel();
                nombreUsuarioTextField = new javax.swing.JTextField();
                nombreUsuarioTextField1 = new javax.swing.JTextField();
                listaTramiteButton = new javax.swing.JButton();
                mainTitleLabel = new javax.swing.JLabel();
                segTramiteButton1 = new javax.swing.JButton();
                crearUsuarioButton = new javax.swing.JButton();
                segTramiteButton3 = new javax.swing.JButton();

                jTextField1.setText("jTextField1");

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                usuarioLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

                usuarioLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                usuarioLabel1.setText("Usuario");

                usuarioLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                usuarioLabel2.setText("Contraseña");

                nombreUsuarioTextField.setToolTipText("");
                nombreUsuarioTextField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nombreUsuarioTextFieldActionPerformed(evt);
                        }
                });

                nombreUsuarioTextField1.setToolTipText("");
                nombreUsuarioTextField1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nombreUsuarioTextField1ActionPerformed(evt);
                        }
                });

                listaTramiteButton.setBackground(new java.awt.Color(0, 0, 0));
                listaTramiteButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
                listaTramiteButton.setForeground(new java.awt.Color(255, 255, 255));
                listaTramiteButton.setText("LISTA DE TRÁMITES");
                listaTramiteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                listaTramiteButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                listaTramiteButtonActionPerformed(evt);
                        }
                });

                mainTitleLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
                mainTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                mainTitleLabel.setText("SISTEMA DE ADMINISTRACIÓN DE USUARIOS");
                mainTitleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

                segTramiteButton1.setBackground(new java.awt.Color(0, 0, 0));
                segTramiteButton1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
                segTramiteButton1.setForeground(new java.awt.Color(255, 255, 255));
                segTramiteButton1.setText("LISTA DE DEPENDENCIAS");
                segTramiteButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                segTramiteButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                segTramiteButton1ActionPerformed(evt);
                        }
                });

                crearUsuarioButton.setBackground(new java.awt.Color(0, 0, 0));
                crearUsuarioButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
                crearUsuarioButton.setForeground(new java.awt.Color(255, 255, 255));
                crearUsuarioButton.setText("CREAR USUARIO");
                crearUsuarioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                crearUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                crearUsuarioButtonActionPerformed(evt);
                        }
                });

                segTramiteButton3.setBackground(new java.awt.Color(0, 0, 0));
                segTramiteButton3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
                segTramiteButton3.setForeground(new java.awt.Color(255, 255, 255));
                segTramiteButton3.setText("LISTA DE USUARIOS");
                segTramiteButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                segTramiteButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                segTramiteButton3ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(usuarioLabel2)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(usuarioLabel)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(32, 32, 32)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(nombreUsuarioTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                                                        .addComponent(nombreUsuarioTextField1))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(mainTitleLabel)
                                                        .addComponent(usuarioLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(58, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(listaTramiteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(segTramiteButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(crearUsuarioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(segTramiteButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(mainTitleLabel)
                                .addGap(35, 35, 35)
                                .addComponent(usuarioLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nombreUsuarioTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(usuarioLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(usuarioLabel2)
                                        .addComponent(nombreUsuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(listaTramiteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(crearUsuarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(segTramiteButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(segTramiteButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void nombreUsuarioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreUsuarioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreUsuarioTextFieldActionPerformed

    private void nombreUsuarioTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreUsuarioTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreUsuarioTextField1ActionPerformed

    private void listaTramiteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaTramiteButtonActionPerformed
        SegTramiteUI frmSegTramite = new SegTramiteUI();
        frmSegTramite.setVisible(true); // hide
    }//GEN-LAST:event_listaTramiteButtonActionPerformed

    private void segTramiteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segTramiteButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_segTramiteButton1ActionPerformed

    private void crearUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearUsuarioButtonActionPerformed
        CrearusuarioUI frmCrearUsuario = new CrearusuarioUI();
        frmCrearUsuario.setVisible(true);
    }//GEN-LAST:event_crearUsuarioButtonActionPerformed

    private void segTramiteButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segTramiteButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_segTramiteButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUI().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton crearUsuarioButton;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JButton listaTramiteButton;
        private javax.swing.JLabel mainTitleLabel;
        private javax.swing.JTextField nombreUsuarioTextField;
        private javax.swing.JTextField nombreUsuarioTextField1;
        private javax.swing.JButton segTramiteButton1;
        private javax.swing.JButton segTramiteButton3;
        private javax.swing.JLabel usuarioLabel;
        private javax.swing.JLabel usuarioLabel1;
        private javax.swing.JLabel usuarioLabel2;
        // End of variables declaration//GEN-END:variables
}
