/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.*;

/**
 *
 * @author villa
 */
public class MainUI extends javax.swing.JFrame{
        private AdministracionUsuario Admins;
                // Set the icon
        /*
        ImageIcon icon = new ImageIcon(getClass().getResource("/resources/banner_principal_vertical.jpg"));
        */
        
        public MainUI() {
                initComponents();
                Admins = new AdministracionUsuario();
        }
        
        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        segTramiteButton = new javax.swing.JButton();
        usuarioLabel = new javax.swing.JLabel();
        ingresarButton = new javax.swing.JButton();
        contrasenaLabel = new javax.swing.JLabel();
        contrasenaUsuarioPasswordField = new javax.swing.JPasswordField();
        mainTitleLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        mainTitleLabel = new javax.swing.JLabel();
        nombreUsuarioTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        segTramiteButton.setBackground(new java.awt.Color(0, 0, 0));
        segTramiteButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        segTramiteButton.setForeground(new java.awt.Color(255, 255, 255));
        segTramiteButton.setText("SEGUIMIENTO DE TRÁMITES");
        segTramiteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        segTramiteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segTramiteButtonActionPerformed(evt);
            }
        });

        usuarioLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        usuarioLabel.setText("Usuario:");

        ingresarButton.setBackground(new java.awt.Color(255, 78, 24));
        ingresarButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        ingresarButton.setForeground(new java.awt.Color(255, 255, 255));
        ingresarButton.setText("INGRESAR");
        ingresarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ingresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarButtonActionPerformed(evt);
            }
        });

        contrasenaLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        contrasenaLabel.setText("Contraseña:");

        contrasenaUsuarioPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasenaUsuarioPasswordFieldActionPerformed(evt);
            }
        });

        mainTitleLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        mainTitleLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        mainTitleLabel1.setText("DOCUMENTARIOS");
        mainTitleLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel3.setText("Login de Administrador");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel1.setText("Servicios para Interesados");

        mainTitleLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        mainTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        mainTitleLabel.setText("SISTEMA DE GESTIÓN DE TRÁMITES");
        mainTitleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        nombreUsuarioTextField.setToolTipText("");
        nombreUsuarioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreUsuarioTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/banner_principal_vertical.jpg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/LOGO_MAIN.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(contrasenaLabel)
                                    .addComponent(usuarioLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreUsuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contrasenaUsuarioPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ingresarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainTitleLabel1)
                            .addComponent(mainTitleLabel)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(segTramiteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainTitleLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioLabel)
                    .addComponent(nombreUsuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contrasenaLabel)
                    .addComponent(contrasenaUsuarioPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(ingresarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(segTramiteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void nombreUsuarioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreUsuarioTextFieldActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_nombreUsuarioTextFieldActionPerformed

        private void ingresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarButtonActionPerformed
                // TODO add your handling code here:
            String filePath = "src/datos/admins.csv";
            BufferedReader br = null; // Se utilizara para tener en memoria la linea que se leeyo previamente en el archivo
                                        // Cada br.readLine() leera la linea siguiente a la almacenada en br


            try {
                br = new BufferedReader(new FileReader(filePath));
                String line;
                boolean firstLine = true; // Para saltar la primera línea (encabezados)

                while ((line = br.readLine()) != null) {
                    if (firstLine) {
                        firstLine = false;
                        continue; // Saltar la primera línea (encabezados)
                    }

                    String[] datos = line.split(";");
                    if (datos.length == 5) { // Verificar existencia de 5 columnas en admins.csv
                        Admins.insertar (datos[1],datos[2],datos[0],datos[4], datos[3]);
  
                    }
                }
            } catch (IOException e) {
                e.printStackTrace(); // Manejo de errores en caso de problemas al leer el archivo
            } finally { // Se ejecuta independientemente de si se produjo una excepción durante la ejecución del código en el bloque try
                if (br != null) {
                    try {
                        br.close(); // Cerrar el BufferedReader para liberar recursos usados en la lectura
                    } catch (IOException e) {
                        e.printStackTrace(); // Manejo de errores al cerrar el archivo
                    }
                }
            }
            String ID = nombreUsuarioTextField.getText();
            String contraseña = contrasenaUsuarioPasswordField.getText();
            
            if (Admins.buscarID(ID) == null)
            {
                JOptionPane.showMessageDialog(this, "Usuario no registrado");
            }
            else if (Admins.buscarID(ID).getID().equalsIgnoreCase(ID) && Admins.buscarID(ID).getContraseña().equalsIgnoreCase(contraseña))
            {    
                // Hacer Invisible la ui
                this.dispose();
                AdminUI admin = new AdminUI(Admins.buscarID(ID)); // El admin existe y sera logueado
                admin.setVisible(true);
            }
            else if (!Admins.buscarID(ID).getID().equalsIgnoreCase(ID) || !Admins.buscarID(ID).getContraseña().equalsIgnoreCase(contraseña))
            {
                JOptionPane.showMessageDialog(this, "Usuario y/o contraseña incorrecto");
            }
                
                
        }//GEN-LAST:event_ingresarButtonActionPerformed

        private void segTramiteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segTramiteButtonActionPerformed
                SegTramiteUI frmSegTramite = new SegTramiteUI();
                this.dispose(); //Cerrar ventana de main
                frmSegTramite.setVisible(true); // Abrir la ventana de seguimiento de tramite
        }//GEN-LAST:event_segTramiteButtonActionPerformed

    private void contrasenaUsuarioPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasenaUsuarioPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasenaUsuarioPasswordFieldActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new MainUI().setVisible(true);
                        }
                });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contrasenaLabel;
    private javax.swing.JPasswordField contrasenaUsuarioPasswordField;
    private javax.swing.JButton ingresarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel mainTitleLabel;
    private javax.swing.JLabel mainTitleLabel1;
    private javax.swing.JTextField nombreUsuarioTextField;
    private javax.swing.JButton segTramiteButton;
    private javax.swing.JLabel usuarioLabel;
    // End of variables declaration//GEN-END:variables
}
