/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author villa
 */
public class SegTramiteUI extends javax.swing.JFrame {

        /**
         * Creates new form SegTramiteUI
         */
        public SegTramiteUI() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                mainTitleLabel = new javax.swing.JLabel();
                idExpLabel = new javax.swing.JLabel();
                idExpTextField = new javax.swing.JTextField();
                jSeparator1 = new javax.swing.JSeparator();
                jSeparator2 = new javax.swing.JSeparator();
                buscarButton = new javax.swing.JButton();
                resultInfoLabel = new javax.swing.JLabel();
                estadoLabel = new javax.swing.JLabel();
                estadoInfoLabel = new javax.swing.JLabel();
                interesadoLabel = new javax.swing.JLabel();
                interesadoNameLabel = new javax.swing.JLabel();
                eventosLabel = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                eventosTable = new javax.swing.JTable();
                jLabel2 = new javax.swing.JLabel();
                jLabel10 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setResizable(false);

                mainTitleLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
                mainTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                mainTitleLabel.setText("SEGUIMIENTO DE TRÁMITE");
                mainTitleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

                idExpLabel.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
                idExpLabel.setText("ID Único de expediente:");

                idExpTextField.setToolTipText("");
                idExpTextField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                idExpTextFieldActionPerformed(evt);
                        }
                });

                buscarButton.setText("Buscar");
                buscarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                buscarButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                buscarButtonActionPerformed(evt);
                        }
                });

                resultInfoLabel.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
                resultInfoLabel.setText("EXPEDIENTE ENCONTRADO / NO ENCONTRADO");

                estadoLabel.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
                estadoLabel.setText("Estado de trámite:");

                estadoInfoLabel.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
                estadoInfoLabel.setText("En proceso / Finalizado");

                interesadoLabel.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
                interesadoLabel.setText("Interesado/a:");

                interesadoNameLabel.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
                interesadoNameLabel.setText("Elon Musk");

                eventosLabel.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
                eventosLabel.setText("Eventos Registrados:");

                eventosTable.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jScrollPane1.setViewportView(eventosTable);

                jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ulima_logo_small.png"))); // NOI18N

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator2)
                                        .addComponent(jSeparator1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(mainTitleLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabel10)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel2)
                                                                .addGap(6, 6, 6))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(estadoLabel)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(estadoInfoLabel))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(interesadoLabel)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(interesadoNameLabel))
                                                                        .addComponent(eventosLabel)
                                                                        .addComponent(resultInfoLabel)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(idExpLabel)
                                                                                .addGap(38, 38, 38)
                                                                                .addComponent(idExpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(0, 10, Short.MAX_VALUE)))))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mainTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(idExpLabel)
                                        .addComponent(idExpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buscarButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resultInfoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(interesadoLabel)
                                        .addComponent(interesadoNameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(estadoLabel)
                                        .addComponent(estadoInfoLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eventosLabel)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void idExpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idExpTextFieldActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_idExpTextFieldActionPerformed

        private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_buscarButtonActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(SegTramiteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(SegTramiteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(SegTramiteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(SegTramiteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new SegTramiteUI().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton buscarButton;
        private javax.swing.JLabel estadoInfoLabel;
        private javax.swing.JLabel estadoLabel;
        private javax.swing.JLabel eventosLabel;
        private javax.swing.JTable eventosTable;
        private javax.swing.JLabel idExpLabel;
        private javax.swing.JTextField idExpTextField;
        private javax.swing.JLabel interesadoLabel;
        private javax.swing.JLabel interesadoNameLabel;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JSeparator jSeparator2;
        private javax.swing.JLabel mainTitleLabel;
        private javax.swing.JLabel resultInfoLabel;
        // End of variables declaration//GEN-END:variables
}
